Выполненное дз № 6
eugene-okulik/sergey_g pull request #10
Opened 2023-11-14 06:21 UTC by Kurchuk

2023-11-14 14:28 UTC, eugene-okulik requested changes
Попробуй реализовать первое задание с чуть менее жестким костылем, который я описал. А если есть время и желание, попробуй даже и сделать еще более универсальный код, который сможет работать с любыми знаками препинания. Спрашивай, если что

2023-11-14 14:28 UTC, eugene-okulik commented on homework/sergey_g/homework_6/task_1.py
> +       'facilisis vitae semper at, dignissim vitae libero'
Правильнее было бы разделить эту строчку так: 
```python
text = (
    'Etiam tincidunt neque erat, quis molestie enim imperdiet vel. Integer urna nisl, '
    + 'facilisis vitae semper at, dignissim vitae libero'
)
```

2023-11-14 14:28 UTC, eugene-okulik commented on homework/sergey_g/homework_6/task_1.py
> +fin_text = text.replace("veling", "veling.")
Это задание в целом решается через костыли, с большего. Можно, конечно количество костылей максимально уменьшить. Но вот этот твой костыль - совсем так себе.

2023-11-14 14:28 UTC, eugene-okulik commented on homework/sergey_g/homework_6/task_1.py
> +fin_text = text.replace("veling", "veling.")
Смотри. Подскажу просто словами как можно закостылить более аккуратно ))  
Ты вот делаешь
```python
for i in range(len(words)):
    words[i] += 'ing'
```
Можно это же и делать, но сделать пару ифов внутри этого цикла: если заканчивается на точку, то удалить точку и добавить "ing.", если заканчивается на запятую, то удалить запятую и добавить "ing,", а в любом другом случае добавлять просто "ing".  
Проверка заканчивается ли слово на точку, например, будет выглядеть так:
```python
if i.endswith('.'):
```

2023-11-14 14:28 UTC, eugene-okulik commented on homework/sergey_g/homework_6/task_1.py
> +fin_text = text.replace("veling", "veling.")
В развитие, можно сделать вообще универсальный код, который сможет нормально сработать с любым знаком препинания.  
Твой костыль прям опирается на конкретные слова, поэтому он мне сильно не нравится.

2023-11-15 09:09 UTC, Kurchuk commented
Использовал твой код из урока, вроде получилось, в целом дается сложно понимание этих циклов, как сделать проверку любого знака препинания ограниченными возможностями пройденного материала не понял, как-то использовал punctuation для этих целей в работе

2023-11-16 05:51 UTC, eugene-okulik approved these changes

2023-11-16 05:51 UTC, merged